### ISSUE TITLE
スタート画面のiMake!の文字と歯車の位置調整

### ISSUE THREAD

**Issue by itomo2** [kathmandu777/i-make#108]
# Overview 
各モードのボタンの端と、文字の端、歯車の端があっていたほうがデザイン的にいいので調整をする。
素材のほうで修正が必要であれば描きなおします。

# Background of the improvement 

# Requirements 

# Considerations 
- 

# Implementation policy 
- 

# Test items 
- 

# Remarks

**Comment by kathmandu777** [comment]
@itomo2

**Comment by kathmandu777** [comment]
一旦 @itomo2  にアサインしました
