### ISSUE TITLE
目の離れ具合の診断の調整

### ISSUE THREAD

**Issue by itomo2** [kathmandu777/i-make#123]
# Overview 
診断モードの目の離れ具合判定を、目の幅 : 目の間 = 1 : 1.3 にする。

# Background of the improvement 

# Requirements 

# Considerations 
- 

# Implementation policy 
- 

# Test items 
- 

# Remarks

**Comment by kathmandu777** [comment]
@itomo2 
```
目の幅 < 目の間 * 1.3
```

のときに、目が離れているという判定をするということであっていますか？

**Comment by itomo2** [comment]
わかりにくくてすみません！
目の幅*1.3 < 目の間
です
