### ISSUE TITLE
プロジェクター投影時にメイクの倍率を自動調整する

### ISSUE THREAD

**Issue by kathmandu777** [kathmandu777/i-make#28]
# Overview 
ぷろじぇくたーから顔までの距離を、mediapipeのreturnするZ座標などを用いて算出し、顔に投影するときの倍率をプログラムで自動調整できるようにする

# Background of the improvement 

# Requirements 

# Considerations 
- 

# Implementation policy 
- 

# Test items 
- 

# Remarks

**Comment by GoRuGoo** [comment]
これ本番環境用プロジェクターないと難しそうですね

**Comment by kathmandu777** [comment]
@GoRuGoo 
事前タスクとしてz座標が使い物になるのかを検証してもらえると助かる！
