### ISSUE TITLE
眉毛の色などを自動変更したい

### ISSUE THREAD

**Issue by GoRuGoo** [kathmandu777/i-make#38]
# Overview 
眉毛の色を自動変更したい

# Background of the improvement 

# Requirements 

# Considerations 
- 

# Implementation policy 
- 

# Test items 
- 

# Remarks

**Comment by kathmandu777** [comment]
@GoRuGoo 
単色画像が入力されることを前提とする (RGB or RGBA)

1. アルファチャンネルは除外する
1. グレースケール化する (width, height) 
2. 1のやつに任意の色をかける
3. アルファチャンネルを復元する

って感じで上手く出来ないかな？
